# Generated by Django 5.1.3 on 2024-11-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCaudalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.FloatField()),
                ('ancho', models.FloatField()),
                ('profundidad_media', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('tecnico_id', models.IntegerField()),
                ('salida_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisTurbidezModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntu', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('tecnico_id', models.IntegerField()),
                ('salida_id', models.IntegerField()),
            ],
        ),
    ]
