# Generated by Django 5.1.3 on 2024-12-05 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salidas_de_campo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('turbidez', 'Turbidez'), ('caudal', 'Caudal'), ('ph', 'pH')], max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('datos', models.JSONField()),
                ('salida_de_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='salidas_de_campo.salidadecampomodel')),
            ],
        ),
    ]
