# Generated by Django 5.1.3 on 2024-11-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoDeAguaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Río'), (2, 'Arroyo'), (3, 'Lago'), (4, 'Humedal')])),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuerpos_de_agua', to='comunidades.comunidadmodel')),
            ],
        ),
    ]
