# Generated by Django 5.1.3 on 2024-11-14 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuerpos_de_agua', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDeCampoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('cuerpos_de_agua_asignados', models.ManyToManyField(related_name='salidas_de_campo', to='cuerpos_de_agua.cuerpodeaguamodel')),
                ('tecnicos_asignados', models.ManyToManyField(related_name='salidas_de_campo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
