# Generated by Django 5.1.3 on 2024-11-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmodel',
            name='url',
            field=models.ImageField(upload_to='galeria/'),
        ),
    ]
